import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner"

const poppins = Poppins ({subsets: ['latin'], weight: ["200", "400", "500", "800"]});
export const metadata: Metadata = {
  title: "Gestor Contraseñas",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body
        className={poppins.className}>{children}
        <Toaster/>
      </body>
    </html>
  );
}
